repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: no-commit-to-branch
    - id: check-merge-conflict
    - id: check-yaml
      exclude: ^charts/.+/templates/
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.6.0
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts
          - --template-files=README.md.gotmpl
